### ISSUE TITLE
NLP Foundations

### ISSUE THREAD

**Issue by Mohana-Murugan** [azminewasi/online-ml-university#3]
# University
<Put University Name>

# Course Topic(s)
<NLP>

# Course Code (If any)
<Put Course Code>

# Course Name
<NLP Foundations>

# Course Session/Year
<Put Course Year>

# Difficulty
<Medium>

# URL
<https://ineuron.ai/course/nlp-foundations>

# Additional Information
<Free course with Certification>

**Comment by azminewasi** [comment]
Please maintain the proper format for submitting new course information.
